function Initialize-Completions
{
    $CompletionsDir = Join-Path $PSScriptRoot "Completions"
    if (-not (Test-Path $CompletionsDir))
    {
        New-Item -ItemType Directory -Path $CompletionsDir | Out-Null
    }

    Write-Host 'Generating zellij completions...' -ForegroundColor DarkGray
    zellij setup --generate-completion powershell | Out-File -FilePath "$CompletionsDir\zellij.ps1" -Encoding utf8

    Write-Host 'Generating bat completions...' -ForegroundColor DarkGray
    bat --completion ps1 | Out-File -FilePath "$CompletionsDir\bat.ps1" -Encoding utf8

    Write-Host 'Generating glow completions...' -ForegroundColor DarkGray
    glow completion powershell | Out-File -FilePath "$CompletionsDir\glow.ps1" -Encoding utf8

    Write-Host 'Generating ripgrep completions...' -ForegroundColor DarkGray
    rg --generate=complete-powershell | Out-File -FilePath "$CompletionsDir\rg.ps1" -Encoding utf8

    Write-Host 'Generating wezterm completions...' -ForegroundColor DarkGray
    wezterm shell-completion --shell power-shell | Out-File -FilePath "$CompletionsDir\wezterm.ps1" -Encoding utf8

    Write-Host 'Generating winget completions...' -ForegroundColor DarkGray
    $wingetContent = @"
Register-ArgumentCompleter -Native -CommandName 'winget' -ScriptBlock {
    param(`$wordToComplete, `$commandAst, `$cursorPosition)
    [Console]::InputEncoding = [Console]::OutputEncoding = `$OutputEncoding = [System.Text.Utf8Encoding]::new()
    `$Local:word = `$wordToComplete.Replace('"', '""')
    `$Local:ast = `$commandAst.ToString().Replace('"', '""')
    winget complete --word="`$Local:word" --commandline "`$Local:ast" --position `$cursorPosition | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)
    }
}
"@
    Set-Content -Path "$CompletionsDir\winget.ps1" -Value $wingetContent -Encoding utf8

    @"
# setup-machine Completions
# Generated by Initialize-Completions

Import-Module`"`$PSScriptRoot\zellij.ps1`"
Import-Module`"`$PSScriptRoot\bat.ps1`"
Import-Module`"`$PSScriptRoot\glow.ps1`"
Import-Module `"`$PSScriptRoot\rg.ps1`"
Import-Module `"`$PSScriptRoot\wezterm.ps1`"
Import-Module `"`$PSScriptRoot\winget.ps1`"

# ============================================================================
# Tools WITHOUT native PowerShell completion generation
# ============================================================================

# eza-community/eza - No --generate-completions support
# ajeetdsouza/zoxide - PR open: https://github.com/ajeetdsouza/zoxide/pull/1052
# sharkdp/fd - No --generate-completions support
# jqlang/jq - No --generate-completions support
# cargo - No --generate-completions support for PowerShell
# dandavison/delta - No --generate-completions support
# tldr-pages/tlrc - No --generate-completions support
# bootandy/dust - No --generate-completions support
# pvolok/mprocs - No --generate-completions support
# hl (highlight) - No --generate-completions support
# alacritty - No PowerShell completion support (bash only)
# kitty - No PowerShell completion support
# ============================================================================
"@ | Out-File -FilePath "$CompletionsDir\setup-machine-completions.ps1" -Encoding utf8

    Import-Module "$CompletionsDir\setup-machine-completions.ps1"
    Write-Host 'Completions loaded for: zellij, bat, glow, rg, wezterm, winget' -ForegroundColor Green
}

function Initialize-Asdf
{
    Write-Host '$ winget install Rustlang.Rustup' -ForegroundColor DarkGray
    winget install Rustlang.Rustup
    Write-Host '$ winget install --id OpenJS.NodeJS.LTS -e' -ForegroundColor DarkGray
    winget install --id OpenJS.NodeJS.LTS -e
    Write-Host '$ winget install Oven-sh.Bun' -ForegroundColor DarkGray
    winget install Oven-sh.Bun
}

function Initialize-Editors
{
    Write-Host '$ winget install --id ZedIndustries.Zed -e' -ForegroundColor DarkGray
    winget install --id ZedIndustries.Zed -e
    Write-Host '$ winget install --id Microsoft.VisualStudioCode -e' -ForegroundColor DarkGray
    winget install --id Microsoft.VisualStudioCode -e
    Write-Host '$ winget install --id Neovim.Neovim -e' -ForegroundColor DarkGray
    winget install --id Neovim.Neovim -e
    Write-Host '$ winget install --id Zellij.Zellij -e' -ForegroundColor DarkGray
    winget install --id Zellij.Zellij -e
}

function Initialize-Unixp
{
    Write-Host '$ winget install --id sharkdp.fd -e' -ForegroundColor DarkGray  # file-search
    winget install --id sharkdp.fd -e
    Write-Host '$ winget install --id dandavison.delta -e' -ForegroundColor DarkGray  # git-tools
    winget install --id dandavison.delta -e
    Write-Host '$ cargo install hl' -ForegroundColor DarkGray  # log-viewer
    cargo install hl
    Write-Host '$ winget install --id tldr-pages.tlrc -e' -ForegroundColor DarkGray  # documentation
    winget install --id tldr-pages.tlrc -e
    Write-Host '$ winget install --id BurntSushi.ripgrep.GNU -e' -ForegroundColor DarkGray  # search
    winget install --id BurntSushi.ripgrep.GNU -e
    Write-Host '$ winget install --id eza-community.eza -e' -ForegroundColor DarkGray  # file-listing
    winget install --id eza-community.eza -e
    Write-Host '$ winget install --id charmbracelet.glow -e' -ForegroundColor DarkGray  # markdown
    winget install --id charmbracelet.glow -e
    Write-Host '$ winget install --id jqlang.jq -e' -ForegroundColor DarkGray  # json
    winget install --id jqlang.jq -e
    Write-Host '$ winget install --id ajeetdsouza.zoxide -e' -ForegroundColor DarkGray  # navigation
    winget install --id ajeetdsouza.zoxide -e
    Write-Host '$ winget install --id sharkdp.bat -e' -ForegroundColor DarkGray  # file-viewing
    winget install --id sharkdp.bat -e
    Write-Host '$ winget install --id bootandy.dust -e' -ForegroundColor DarkGray  # disk-usage
    winget install --id bootandy.dust -e
    Write-Host '$ winget install --id pvolok.mprocs -e' -ForegroundColor DarkGray  # process-manager
    winget install --id pvolok.mprocs -e
}

function Initialize-Terminal
{
    Write-Host '$ winget install --id Microsoft.PowerShell' -ForegroundColor DarkGray
    winget install --id Microsoft.PowerShell
    Write-Host '$ winget install --id avborup.kitty' -ForegroundColor DarkGray
    winget install --id avborup.kitty
    Write-Host '$ winget install --id Alacritty.Alacritty' -ForegroundColor DarkGray
    winget install --id Alacritty.Alacritty
    Write-Host '$ winget install --id wez.wezterm' -ForegroundColor DarkGray
    winget install --id wez.wezterm
}
