#!/usr/bin/env bash

dotfiles=${DOTFILES:-$HOME/.dotfiles}
data=${XDG_DATA_HOME:-$HOME/.local/share}
if [[ ! -d "$data/dotbot"  ]]; then
    echo -e "\033[1;33m--------------- cloning dotbot ----------------\033[0m"
    git clone https://github.com/anishathalye/dotbot "$data/dotbot" --recurse-submodules --jobs 8
fi

if [[ ! -d "$data/dotbot-plugins"  ]]; then
    echo -e "\033[1;33m--------------- cloning dotbot-plugins ----------------\033[0m"
    git clone https://github.com/ggallovalle/dotbot-plugins "$data/dotbot-plugins" --recurse-submodules --jobs 8
fi

"$data/dotbot/bin/dotbot" -d "$dotfiles" --plugin-dir \
    "$data/dotbot-plugins" -c "$dotfiles/config.yml" "$@"

