#!/usr/bin/env bash
# fail in case any of the commands fails
set -e
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "$RED Cloning submodules$NC"
git submodule update --init --recursive

echo -e "$RED Linking dotfiles$NC"
bash -c "${BASEDIR}/dotbot --only link"
if [[ ! -d ${XDG_DATA_HOME:-$HOME/.local/share}/zinit/bin ]]; then
    echo -e "$RED Cloning zinit$NC"
    mkdir ${XDG_DATA_HOME:-$HOME/.local/share}/zinit
    git clone https://github.com/zdharma/zinit.git ${XDG_DATA_HOME:-$HOME/.local/share}/zinit/bin
fi

if [[ ! -x $HOME/.emacs.d/bin/doom ]]; then
    if ! command -v emacs; then
        echo -e "$RED Installing emacs$NC"
        sudo pacman -S emacs
    fi
    echo -e "$RED Cloning doom emacs$NC"
    git clone --depth 1 https://github.com/hlissner/doom-emacs $HOME/.emacs.d
    echo -e "$RED Installing doom emacs"
    $HOME/.emacs.d/bin/doom install --no-config
fi
if [[ -x $HOME/.emacs.d/bin/doom ]]; then
    $HOME/.emacs.d/bin/doom doctor
fi

if [[ ! -d ${XDG_DATA_HOME:-$HOME/.local/share}/asdf ]]; then
    echo -e "$RED Cloning asdf$NC"
    git clone https://github.com/asdf-vm/asdf.git ${XDG_DATA_HOME:-$HOME/.local/share}/asdf
    cd ${XDG_DATA_HOME:-$HOME/.local/share}/asdf
    git checkout "$(git describe --abbrev=0 --tags)"
    cd -
    ${XDG_DATA_HOME:-$HOME/.local/share}/asdf/bin/asdf plugin-add nodejs https://github.com/ggallovalle/asdf-nodejs
    bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
    bash -c "${BASEDIR}/dotbot --only asdf"
fi

if [[ $(echo $SHELL) = "/bin/bash" ]]; then
    echo -e "$RED Change default shell to zsh$NC"
    chsh -s $(which zsh)
fi

if [[ ! -d ${XDG_DATA_HOME:-$HOME/.local/share}/fonts ]]; then
    echo -e "$RED Setting up fonts$NC"
    cd ${XDG_DATA_HOME:-$HOME/.local/share}/fonts
    curl -O https://srv-store6.gofile.io/download/wzom5C/fonts.zip
    unzip fonts.zip
    rm fonts.zip
    cd -
fi

echo '----------------'
echo 'Everything is OK'

