#!/bin/sh

LUAROCKS_SYSCONFDIR='/etc/luarocks' exec '/usr/bin/lua5.3' -e 'package.path="/usr/share/lua/5.4/?.lua;/usr/share/lua/5.4/?/init.lua;/usr/lib/lua/5.4/?.lua;/usr/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/home/kbroom/.luarocks/share/lua/5.4/?.lua;/home/kbroom/.luarocks/share/lua/5.4/?/init.lua";package.cpath="/usr/lib/lua/5.4/?.so;/usr/lib/lua/5.4/loadall.so;./?.so;/home/kbroom/.luarocks/lib/lua/5.4/?.so"' '/usr/bin/luarocks' --project-tree /home/kbroom/.config/awesome/lua_modules "$@"
