#compdef typspec
# @generated by usage-cli from usage spec
local curcontext="$curcontext"

_typspec() {
  typeset -A opt_args
  local curcontext="$curcontext"

  if ! type -p usage &> /dev/null; then
      echo >&2
      echo "Error: usage CLI not found. This is required for completions to work with typspec." >&2
      echo "See https://usage.jdx.dev for more information." >&2
      return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/typspec_spec"
  if [[ ! -f "$spec_file" ]]; then
    typspec usage >| "$spec_file"
  fi
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_typspec" ]; then
    _typspec "$@"
else
    compdef _typspec typspec
fi
