# setup-machine Completions
# Generated by Initialize-Completions

. "$PSScriptRoot\bat.ps1"
. "$PSScriptRoot\glow.ps1"
. "$PSScriptRoot\rg.ps1"
. "$PSScriptRoot\wezterm.ps1"
. "$PSScriptRoot\winget.ps1"

# ============================================================================
# Tools WITHOUT native PowerShell completion generation
# ============================================================================

# eza-community/eza - No --generate-completions support
# ajeetdsouza/zoxide - PR open: https://github.com/ajeetdsouza/zoxide/pull/1052
# sharkdp/fd - No --generate-completions support
# jqlang/jq - No --generate-completions support
# cargo - No --generate-completions support for PowerShell
# dandavison/delta - No --generate-completions support
# tldr-pages/tlrc - No --generate-completions support
# bootandy/dust - No --generate-completions support
# pvolok/mprocs - No --generate-completions support
# hl (highlight) - No --generate-completions support
# alacritty - No PowerShell completion support (bash only)
# kitty - No PowerShell completion support
# ============================================================================
