# Inserts a blank line between shell prompts
# Use custom format
format = """
[┌──────>](bold green) $package$nodejs$elixir$python$ruby$dart$php$dotnet$java$scala$kotlin
([│](bold green)$git_branch $git_commit $git_state $git_status)
[│](bold green)$directory$status
[└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the package module, hiding it from the prompt completely
[package]
display_private = true

[status]
disabled = false
symbol = "🚨"
