[tools]
bun = "1.3.12"
codex = "latest"
copilot = "latest"
delta = "latest"
fzf = "latest"
gemini-cli = "latest"
github-cli = "latest"
"github:pamburus/hl" = "latest"
"gitlab:gitlab-org/cli" = { version = "latest", exe = "glab" }
just = "latest"
lazygit = "latest"
node = "22.19.0"
opencode = "latest"
starship = "latest"
tlrc = "latest"
usage = "latest"
yazi = "latest"
zoxide = "latest"
jq = "latest"
glow = "latest"
chezmoi = "latest"
neovim = "latest"
