#!/bin/bash
DIR=$(dirname "$0")
source $DIR/utils.sh
# exa:
# needs to be installed from source

# keychain:
# pkgs=(keychain)
# sudo apt install ${pkgs[@]}

# exa:
# sudo apt-add-repository -u ppa:fish-shell/release-3
# sudo apt-get install fish

# starship:
# curl -fsSL https://starship.rs/install.sh | bash

# python with asdf:
sudo apt-get update; sudo apt-get install --no-install-recommends make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev