#!/bin/bash
DIR=$(dirname "$0")
source $DIR/utils.sh

g_clonner "doom emacs" https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
g_k "Doom emacs installed"
~/.emacs.d/bin/doom doctor
# install required packages
paru -S ripgrep jq cmake scrot shellcheck
npm add -g stylelint js-beautify
doom doctor
