#!/bin/bash
DIR=$(dirname "$0")
source $DIR/utils.sh

GHQ_ROOT=${GHQ_ROOT:-$HOME/ghq}
declare -A grepos

grepos['laravel/framework']='framework, php, laravel'
grepos['django/django']='framework, py, django'
grepos['dotnet/aspnetcore']='framework, c#, dotnet'
grepos['nestjs/typeorm']='lib, ts, nestjs'
grepos['nestjs/passport']='lib, ts, nestjs'
grepos['vincit/objection.js']='lib, js'
grepos['rails/rails']='framework, ruby, rails'
grepos['rspec/rspec-core']='test, ruby, rspec'
grepos['rspec/rspec-mocks']='test, ruby, rspec'
grepos['rspec/rspec-expectations']='test, ruby, rspec'
grepos['nestjs/nest']='framework, nestjs, ts'
grepos['nestjs/cqrs']='nestjs, ts, cqrs'
grepos['gcanti/fp-ts-fluture']='fp-ts, ts'
grepos['gcanti/io-ts']='fp-ts, ts'
#_others
g_w "OTHERS REPOSITORIES"
for key in ${!grepos[@]}; do
    directory=$GHQ_ROOT/github.com/$key
    repo_path=$key
    if [[ ! -d $directory ]]; then
        # clone
        ghq get $repo_path
        IFS=', ' read -r -a tags <<<${grepos[$key]}
        for t in ${tags[@]}; do
            # tag
            tmsu tag $directory $t
        done
    fi
    g_k "$key" '->' ${grepos[$key]}
done

# my repositories
declare -A myrepos

# myrepos[pkginfo]='project, cli, py'
# myrepos['objection-utils']='project, lib, ts'

g_w "MINE REPOSITORIES"
for key in ${!myrepos[@]}; do
    directory=$GHQ_ROOT/github.com/ggallovalle/$key
    repo_path=ggallovalle/$key
    if [[ ! -d $directory ]]; then
        # clone
        ghq get -p $repo_path
        IFS=', ' read -r -a tags <<<${myrepos[$key]}
        for t in ${tags[@]}; do
            # tag
            tmsu tag $directory $t
        done
    fi
    g_k "$key" '->' ${myrepos[$key]}
done
