#!/bin/bash
DIR=$(dirname "$0")
source $DIR/utils.sh

g_pkg tmux tmux
g_clonner "tmux plugin manager" https://github.com/tmux-plugins/tpm "$XDG_DATA_HOME/tmux/tpm"
if [[ -d "$XDG_DATA_HOME/tmux" ]]; then
    bash -c "$XDG_DATA_HOME/tmux/tpm/bindings/install_plugins"
    g_k 'tmux plugins installed'
fi
